#!/bin/sh

set -e

modelist=""
cleanup() {
   rm -f "${modelist}"
}
trap cleanup EXIT
modelist=$(mktemp)
xrandr -d :0 | tail -n+2 | sed 's/[+*]//' > "${modelist}"
cat ${modelist}
output=""

while read -r line; do
   mode=$(echo "${line}" | awk '{print $1}')
   echo "Select mode ${mode}"
   if echo "$line" | grep -q HDMI-1; then
      output=HDMI-1
   elif echo "$line" | grep -q XWAYLAND0; then
      output=XWAYLAND0
   elif echo "$line" | grep -q HDMI-2; then
      output=HDMI-2
      xrandr --output "HDMI-1" --mode "1920x1080" --rate "60.00"
   else
      echo "Test rates in $line"
      for rate in $(echo "${line}" | awk '{for (i=2; i<=NF; i++) print $i}'); do
         echo xrandr --output "${output}" --mode "${mode}" --rate "${rate}"
         xrandr --output "${output}" --mode "${mode}" --rate "${rate}"
         sleep 5
      done
   fi
done < "${modelist}"
