#!/bin/sh

script_dir=$(cd $(dirname $0) && pwd)

sudo apt update
sudo apt install -y tmux vim fonts-powerline
sudo apt install -y git bc bison flex libssl-dev make build-essential time pkg-config
sudo apt install -y openocd gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib picocom cmake libusb-1.0-0-dev

cd $HOME

cp -f "${script_dir}/.vimrc" "${HOME}"
mkdir -p "${HOME}/.vim/colors"
cp -f "${script_dir}/molokai.vim" "${HOME}/.vim/colors"
if [ ! -e ~/.vim/bundle/Vundle.vim ]; then
   git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
fi

if [ ! -d pico-sdk ]; then
   git clone https://github.com/raspberrypi/pico-sdk
   cd pico-sdk
   git submodule init
   git submodule update
   cd ..
fi

if [ ! -d picoprobe ]; then
   git clone https://github.com/raspberrypi/picoprobe.git
fi

if [ ! -d pico-examples ]; then
   git clone https://github.com/raspberrypi/pico-examples
fi

if [ ! -d picotool ]; then
   git clone https://github.com/raspberrypi/picotool
   cd picotool
   sudo cp udev/99-picotool.rules /etc/udev/rules.d/
   mkdir build
   cd build
   cmake ..
   make
   sudo make install
fi
wget https://github.com/raspberrypi/picoprobe/releases/download/picoprobe-cmsis-v1.0.3/debugprobe.uf2
