#!/bin/sh

if ! grep -q "BOOT COUNT" "$HOME/.bashrc"; then
   echo 0 > "$HOME/reboot-count"

cat <<EOF >> "${HOME}/.bashrc"
if [ -f /boot/reboot ]; then
   count=\$(cat \${HOME}/reboot-count)
   count=\$((count + 1))
   echo -n \$count > "\${HOME}/reboot-count"
   echo "BOOT COUNT \$count"
   sleep 5
   sudo reboot "${1}"
else
   echo 0 > "\${HOME}/reboot-count"
fi
EOF
fi
