#!/bin/sh

match="xhci_hcd/4p"

if lsusb | grep -q "${match}"; then
   echo ""
else
   echo "rescan"
   sudo su -c "echo 1 > /sys/bus/pci/rescan"
fi
sleep 1

sudo su -c "echo 1 > /sys/bus/pci/devices/0000\:00\:00.0/remove"
sudo su -c "lspci"
sudo su -c "lsusb"
sleep 1
sudo su -c "echo 1 > /sys/bus/pci/rescan"
sleep 3
sudo su -c "lspci"
lsusb -t
sudo vclog -m | egrep -i "xhci|vli" | tail -n5
if lsusb | grep -q "${match}"; then
	exit 0
fi
exit 1
